Repository lapce/lapce, pull requests merged in 2022-05, with the labels that each got.

#473 Display problem type icon in front of counter
  lapce-ui/src/status.rs
Labels: A-ui, C-improvement

#474 Introduce `ReadOnlyString`
  lapce-ui/src/explorer.rs
  lapce-ui/src/panel.rs
  lapce-ui/src/plugin.rs
  lapce-ui/src/problem.rs
  lapce-ui/src/search.rs
  lapce-ui/src/source_control.rs
  lapce-ui/src/tab.rs
  lapce-ui/src/terminal.rs
Labels: C-perf

#478 Propagate events to hidden if necessary, remove some boxes
  lapce-ui/src/panel.rs
  lapce-ui/src/settings.rs
  lapce-ui/src/tab.rs
Labels: C-improvement

#484 Run fmt on PRs
  .github/workflows/pr.yml
  lapce-data/src/container.rs
  lapce-ui/src/app.rs
Labels: A-dev

#479 Don't draw shortcut names outside of the cells
  Cargo.lock
  lapce-data/src/data.rs
  lapce-data/src/split.rs
  lapce-ui/src/keymap.rs
  lapce-ui/src/split.rs
Labels: C-bug, A-ui, S-waiting-for-author

#493 Use `&'static str` in `LapceIcon`
  lapce-ui/src/editor/header.rs
  lapce-ui/src/editor/tab_header.rs
  lapce-ui/src/find.rs
  lapce-ui/src/panel.rs
  lapce-ui/src/status.rs
  lapce-ui/src/svg.rs
  lapce-ui/src/tab.rs
  lapce-ui/src/terminal.rs
Labels: C-cleanup

#494 Remove more unused code
  lapce-data/src/split.rs
  lapce-ui/src/app.rs
  lapce-ui/src/code_action.rs
  lapce-ui/src/completion.rs
  lapce-ui/src/editor.rs
  lapce-ui/src/editor/diff_split.rs
  lapce-ui/src/editor/tab_header.rs
  lapce-ui/src/explorer.rs
  lapce-ui/src/hover.rs
  lapce-ui/src/keymap.rs
  lapce-ui/src/lib.rs
  lapce-ui/src/outline.rs
  lapce-ui/src/palette.rs
  lapce-ui/src/panel.rs
  lapce-ui/src/picker.rs
  lapce-ui/src/plugin.rs
  lapce-ui/src/problem.rs
  lapce-ui/src/scroll.rs
  lapce-ui/src/search.rs
  lapce-ui/src/settings.rs
  lapce-ui/src/signature.rs
  lapce-ui/src/source_control.rs
  lapce-ui/src/split.rs
  lapce-ui/src/svg.rs
  lapce-ui/src/terminal.rs
Labels: C-cleanup

#460 support count in word movement commands
  lapce-core/src/buffer.rs
  lapce-core/src/buffer/test.rs
  lapce-core/src/word.rs
  lapce-core/src/word/test.rs
  lapce-data/src/document.rs
Labels: C-feature, A-editor

#459 implement top_of_window and bottom_of_window
  defaults/keymaps-common.toml
  lapce-core/src/command.rs
  lapce-data/src/command.rs
  lapce-data/src/data.rs
  lapce-data/src/editor.rs
  lapce-ui/src/editor/view.rs
Labels: C-feature, A-editor

#432 Fix: remove minimum window size constraint
  lapce-ui/src/app.rs
Labels: C-bug

#564 fix: don't overwrite permissions
  lapce-proxy/src/buffer.rs
Labels: A-editor
