Repository lapce/lapce, pull requests merged in 2022-06, with the labels that each got.

#573 Indicate minimum toolchain version preventing #572
  README.md
  docs/new-contributor-guide-developer.md
Labels: A-dev, C-improvement

#586 Add `Plugin load failed` message
  lapce-ui/src/plugin.rs
Labels: A-ui, C-improvement

#622 Added result numbers to the FindBox widget.
  lapce-ui/src/editor.rs
  lapce-ui/src/find.rs
Labels: A-editor

#625 [TreeSitter] Add elm language support
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-core/src/language.rs
  lapce-ui/Cargo.toml
Labels: A-syntax

#549 Golang Support
  Cargo.lock
  lapce-data/src/editor.rs
  lapce-proxy/Cargo.toml
  lapce-proxy/src/buffer.rs
  lapce-proxy/src/lsp.rs
  lapce-proxy/src/plugin.rs
  lapce-rpc/src/plugin.rs
Labels: C-feature, A-lsp

#670 Add shift-delete/shift-backspace to keymaps
  defaults/keymaps-common.toml
Labels: A-keymap

#666 Impl searching for symbols in workspace
  defaults/keymaps-macos.toml
  defaults/keymaps-nonmacos.toml
  lapce-data/src/command.rs
  lapce-data/src/data.rs
  lapce-data/src/palette.rs
  lapce-data/src/proxy.rs
  lapce-proxy/src/dispatch.rs
  lapce-proxy/src/lsp.rs
  lapce-rpc/src/proxy.rs
  lapce-ui/src/palette.rs
Labels: A-lsp

#684 Add a missing step for caching to CI
  .github/workflows/pr.yml
Labels: A-dev

#685 Fix crashing on workspace symbol search
  lapce-data/src/palette.rs
Labels: A-ui, A-lsp

#690 add syntax highlighting support for Bash and Zig
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-core/src/language.rs
  lapce-ui/Cargo.toml
Labels: A-syntax

#691 Add button for committing to Git
  lapce-data/src/source_control.rs
  lapce-ui/src/button.rs
  lapce-ui/src/lib.rs
  lapce-ui/src/source_control.rs
Labels: A-git

#706 Added multiple file icons
  icons/file_type_css.svg
  icons/file_type_html.svg
  icons/file_type_js.svg
  icons/file_type_lua.svg
  icons/file_type_python.svg
  icons/file_type_ts.svg
  icons/file_type_zip.svg
  lapce-ui/src/svg.rs
Labels: A-ui

#712 Upgrade lsp-types to 0.93
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-data/Cargo.toml
  lapce-data/src/editor.rs
  lapce-proxy/Cargo.toml
  lapce-proxy/src/lsp.rs
  lapce-rpc/Cargo.toml
  lapce-ui/Cargo.toml
  lapce-ui/src/editor.rs
  lapce-ui/src/problem.rs
  lapce-ui/src/svg.rs
  lapce-ui/src/tab.rs
Labels: A-lsp
