Repository lapce/lapce, pull requests merged in 2022-10, with the labels that each got.

#1422 Check if get_editor request is non-scratch before early-returning
  lapce-data/src/data.rs
Labels: C-bug, A-editor

#1401 Merge semantic and syntax highlighting
  lapce-data/src/document.rs
Labels: A-lsp, A-syntax

#1486 Update Changelog.md with 0.2.1 changes
  CHANGELOG.md
Labels: A-documentation

#1484 Split up SettingItem code
  lapce-data/src/document.rs
  lapce-ui/src/editor/view.rs
  lapce-ui/src/settings.rs
  lapce-ui/src/tab.rs
Labels: A-dev

#1483 UI: Fix issue where 1st tab shows the close icon...
  CHANGELOG.md
  lapce-ui/src/editor/tab.rs
  lapce-ui/src/editor/tab_header_content.rs
Labels: C-bug, A-ui

#1523 ci: bump checkout action
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: A-dev

#1517 Add support for empty setting items
  lapce-ui/src/settings.rs
Labels: A-ui

#1472 feat(tree-sitter): add sql language
  CHANGELOG.md
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-core/src/language.rs
  lapce-core/src/syntax/highlight.rs
  lapce-ui/Cargo.toml
Labels: A-syntax

#1554 feat(tree-sitter): Add XML support
  CHANGELOG.md
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-core/src/language.rs
  lapce-core/src/syntax/highlight.rs
  lapce-ui/Cargo.toml
Labels: A-syntax

#1565 Several fixes to the About modal
  lapce-ui/src/about.rs
Labels: A-ui

#1609 Add syntax highlighting for erlang.
  CHANGELOG.md
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-core/queries/erlang/highlights.scm
  lapce-core/src/language.rs
  lapce-core/src/syntax/highlight.rs
  lapce-ui/Cargo.toml
Labels: A-syntax

#1587 Add g++ in Ubuntu building from source guide
  docs/building-from-source.md
Labels: A-documentation

#1421 Highlight matching brackets
  CHANGELOG.md
  lapce-core/src/syntax/mod.rs
  lapce-core/src/word.rs
  lapce-data/src/document.rs
  lapce-ui/src/editor.rs
Labels: C-feature, A-ui
