Repository lapce/lapce, pull requests merged in 2022-09, with the labels that each got.

#1044 Limit how far the bottom panel can be resized
  lapce-ui/src/tab.rs
Labels: A-ui

#1084 Use host shell in terminal when running inside Flatpak
  lapce-proxy/src/terminal.rs
Labels: A-terminal, C-improvement

#957 Replace tree-sitter highlighting code with Helix's impl
  Cargo.lock
  defaults/dark-theme.toml
  defaults/light-theme.toml
  lapce-core/Cargo.toml
  lapce-core/queries/markdown.inline/highlights.scm
  lapce-core/queries/markdown.inline/injections.scm
  lapce-core/queries/markdown/highlights.scm
  lapce-core/queries/markdown/injections.scm
  lapce-core/src/buffer.rs
  lapce-core/src/editor.rs
  lapce-core/src/language.rs
  lapce-core/src/style.rs
  lapce-core/src/syntax.rs
  lapce-core/src/syntax/edit.rs
  lapce-core/src/syntax/highlight.rs
  lapce-core/src/syntax/mod.rs
  lapce-core/src/syntax/util.rs
  lapce-core/src/word.rs
  lapce-data/src/document.rs
  lapce-data/src/history.rs
  lapce-data/src/markdown/mod.rs
Labels: A-syntax

#1127 Update Julia highlighting
  Cargo.lock
  defaults/dark-theme.toml
  defaults/light-theme.toml
  lapce-core/queries/julia/highlights.scm
  lapce-core/src/style.rs
Labels: A-syntax

#1153 Adding support for the dart language (help needed)
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-core/src/language.rs
  lapce-core/src/syntax/highlight.rs
  lapce-ui/Cargo.toml
Labels: C-improvement, A-syntax

#1050 Collapsible problem groups
  lapce-data/src/command.rs
  lapce-data/src/data.rs
  lapce-data/src/problem.rs
  lapce-ui/src/problem.rs
  lapce-ui/src/tab.rs
Labels: C-feature, A-ui

#1145 add new highlights according to new tree-sitter implementation
  lapce-core/queries/bash/highlights.scm
  lapce-core/queries/c/highlights.scm
  lapce-core/queries/cpp/highlights.scm
  lapce-core/queries/css/highlights.scm
  lapce-core/queries/javascript/highlights.scm
  lapce-core/queries/typescript/highlights.scm
  lapce-core/queries/zig/highlights.scm
  lapce-core/src/language.rs
Labels: A-syntax

#1163 terminal: Implement text selection and copy/paste functionality in terminal mode
  defaults/keymaps-nonmacos.toml
  lapce-core/src/mode.rs
  lapce-data/src/keypress/loader.rs
  lapce-data/src/terminal.rs
  lapce-ui/src/terminal.rs
Labels: A-terminal, C-improvement

#1161 feat: add Svelte & LaTeX
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-core/queries/latex/highlights.scm
  lapce-core/queries/latex/injections.scm
  lapce-core/src/language.rs
  lapce-core/src/syntax/highlight.rs
  lapce-ui/Cargo.toml
Labels: A-syntax

#1179 Window Tab improvements
  lapce-ui/src/app.rs
  lapce-ui/src/tab.rs
  lapce-ui/src/window.rs
Labels: A-ui

#1190 fix: Utilize active/inactive tab colors from theme
  lapce-ui/src/editor/tab.rs
Labels: A-ui

#1250 fix: too long socket
  lapce-data/src/proxy.rs
Labels: A-remote

#1252 Check whether index exists when using EnsureEditorTabActiveVisible
  lapce-ui/src/editor/tab.rs
Labels: C-crash 💥

#1246 Unify Palette/Completion with List widget
  lapce-data/src/command.rs
  lapce-data/src/completion.rs
  lapce-data/src/data.rs
  lapce-data/src/editor.rs
  lapce-data/src/lib.rs
  lapce-data/src/list.rs
  lapce-data/src/palette.rs
  lapce-ui/src/completion.rs
  lapce-ui/src/lib.rs
  lapce-ui/src/list.rs
  lapce-ui/src/palette.rs
  lapce-ui/src/tab.rs
Labels: A-ui

#1244 Prettier plugin panel
  .gitignore
  lapce-ui/src/plugin.rs
Labels: A-ui

#1263 fix: dont lie to LSP, we didnt implement workspace/configuration
  lapce-proxy/src/plugin/lsp.rs
Labels: A-lsp

#1271 Make PSP/LSP api use number and string identifiers
  Cargo.lock
  lapce-data/Cargo.toml
  lapce-proxy/Cargo.toml
  lapce-proxy/src/plugin/lsp.rs
  lapce-proxy/src/plugin/mod.rs
  lapce-proxy/src/plugin/psp.rs
  lapce-proxy/src/plugin/wasi.rs
  lapce-ui/Cargo.toml
Labels: C-bug, A-lsp, A-plugins

#1272 add new highlights for elm, jsx and fix tsx highlights
  lapce-core/queries/elm/highlights.scm
  lapce-core/queries/jsx/highlights.scm
  lapce-core/src/language.rs
Labels: A-syntax

#1279 Defaults: change default line height to 1.35
  defaults/settings.toml
Labels: A-ui

#1297 Use upstream repo for tree-sitter-haxe
  Cargo.lock
  lapce-core/Cargo.toml
Labels: A-syntax

#1299 Kotlin tree-sitter support
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-core/queries/kotlin/highlights.scm
  lapce-core/queries/kotlin/injections.scm
  lapce-core/src/language.rs
  lapce-core/src/syntax/highlight.rs
  lapce-ui/Cargo.toml
Labels: A-syntax

#1344 Replace Branch-Selector dropdown with a List
  lapce-data/src/command.rs
  lapce-data/src/data.rs
  lapce-data/src/lib.rs
  lapce-data/src/source_control.rs
  lapce-data/src/title.rs
  lapce-ui/src/completion.rs
  lapce-ui/src/list.rs
  lapce-ui/src/palette.rs
  lapce-ui/src/tab.rs
  lapce-ui/src/title.rs
Labels: A-ui

#1357 Fix proxy hang due to held lock
  lapce-rpc/src/proxy.rs
Labels: C-bug

#1356 Fix edit crash
  lapce-core/src/syntax/edit.rs
Labels: C-crash 💥, A-syntax

#1338 Added setting to disable automatic closing of matching pairs
  defaults/settings.toml
  lapce-core/src/editor.rs
  lapce-data/src/config.rs
  lapce-data/src/document.rs
  lapce-data/src/editor.rs
Labels: A-editor

#1314 Cases get handled correctly when generating keyboard shortcuts from UI
  lapce-ui/src/keymap.rs
Labels: A-keymap

#1353 feat(lsp): implement syntax aware selection
  defaults/keymaps-common.toml
  lapce-core/src/command.rs
  lapce-core/src/cursor.rs
  lapce-data/src/command.rs
  lapce-data/src/document.rs
  lapce-data/src/editor.rs
  lapce-data/src/lib.rs
  lapce-data/src/selection_range.rs
  lapce-proxy/src/dispatch.rs
  lapce-proxy/src/plugin/mod.rs
  lapce-proxy/src/plugin/psp.rs
  lapce-rpc/src/proxy.rs
  lapce-ui/src/editor.rs
Labels: C-feature, A-editor

#1375 Lua support
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-core/queries/lua/highlights.scm
  lapce-core/src/language.rs
  lapce-core/src/syntax/highlight.rs
  lapce-ui/Cargo.toml
Labels: C-feature, A-syntax

#1396 Indicate to download_volt that plugins without wasm files should not have wasm files
  lapce-data/src/plugin.rs
Labels: A-plugins

#1390 Chore/remove unused deps
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-data/Cargo.toml
  lapce-ui/Cargo.toml
Labels: A-dev

#1326 add vue highlight support
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-core/src/language.rs
  lapce-core/src/syntax/highlight.rs
  lapce-proxy/src/buffer.rs
  lapce-ui/Cargo.toml
Labels: A-syntax

#1371 Add sticky headers for json files
  lapce-core/src/language.rs
Labels: A-ui

#1403 Clean up a few `Selection` methods
  lapce-core/src/selection.rs
Labels: A-dev

#1404 Log panics with full backtrace as errors
  Cargo.lock
  lapce-ui/Cargo.toml
  lapce-ui/src/app.rs
Labels: C-feature, A-dev

#1411 Sort language list alphabetically
  lapce-core/Cargo.toml
  lapce-core/src/language.rs
  lapce-core/src/syntax/highlight.rs
  lapce-ui/Cargo.toml
Labels: A-dev
