Repository lapce/lapce, pull requests merged in 2022-04, with the labels that each got.

#364 Adds alternative keymap to normal_mode
  defaults/keymaps-common.toml
Labels: C-feature

#372 Avoid cloning compare strings
  lapce-data/src/buffer.rs
  lapce-data/src/editor.rs
Labels: C-cleanup

#373 Clean up parts of `move_offset`
  lapce-data/src/buffer.rs
Labels: C-cleanup

#298 Remove duplicate code action module, remove unused field
  lapce-data/src/code_action.rs
  lapce-data/src/lib.rs
  lapce-ui/src/code_action.rs
Labels: C-cleanup

#330 Clean up gutter painting a bit
  lapce-ui/src/editor/gutter.rs
Labels: C-cleanup

#378 Improve text measurement
  lapce-data/src/config.rs
  lapce-data/src/data.rs
  lapce-data/src/editor.rs
  lapce-ui/src/editor.rs
  lapce-ui/src/editor/gutter.rs
  lapce-ui/src/editor/view.rs
  lapce-ui/src/terminal.rs
Labels: C-perf

#333 Remove unnecessary field and function
  lapce-data/src/buffer.rs
Labels: C-cleanup

#381 Changed mode indicator color to match theme
  defaults/dark-theme.toml
  defaults/light-theme.toml
  lapce-data/src/config.rs
  lapce-ui/src/status.rs
Labels: C-feature

#392 Don't panic if terminal does not exist
  lapce-proxy/src/dispatch.rs
Labels: C-bug

#389 Fix crash when tab title is root or invalid
  lapce-ui/src/tab.rs
Labels: C-bug

#350 Refactor buffer editing to allow testing
  lapce-data/src/buffer.rs
  lapce-data/src/buffer/data.rs
  lapce-data/src/buffer/decoration.rs
  lapce-data/src/data.rs
  lapce-data/src/db.rs
  lapce-data/src/editor.rs
  lapce-data/src/movement.rs
  lapce-data/src/palette.rs
  lapce-ui/src/editor.rs
  lapce-ui/src/editor/gutter.rs
  lapce-ui/src/editor/header.rs
  lapce-ui/src/editor/tab.rs
  lapce-ui/src/editor/view.rs
  lapce-ui/src/settings.rs
  lapce-ui/src/tab.rs
Labels: C-cleanup, C-tests

#380 Add edit operation test framework and a few initial tests
  lapce-data/src/buffer.rs
  lapce-data/src/buffer/data.rs
  lapce-data/src/editor.rs
  lapce-data/src/editor/commands/insert_tab.rs
  lapce-data/src/editor/commands/mod.rs
  lapce-data/src/editor/commands/redo.rs
  lapce-data/src/editor/commands/test/mod.rs
  lapce-data/src/editor/commands/test/test_state.rs
  lapce-data/src/editor/commands/undo.rs
Labels: C-tests

#399 Fix parsing multiple selection ranges in TestState
  lapce-data/src/editor/commands/test/test_state.rs
Labels: C-bug, C-tests

#409 Remove duplicate `scroll` module
  lapce-data/src/lib.rs
  lapce-data/src/scroll.rs
Labels: C-cleanup

#410 Release cursor request when settings panel is closed
  lapce-ui/src/settings.rs
Labels: C-bug

#338 Close tabs on mouse up, don't start dragging until tab is actually dragged
  lapce-ui/src/editor/tab_header_content.rs
Labels: C-feature

#412 Refactor indent and outdent line edits
  lapce-data/src/editor.rs
  lapce-data/src/editor/commands/indent_line.rs
  lapce-data/src/editor/commands/mod.rs
  lapce-data/src/editor/commands/outdent_line.rs
Labels: C-tests

#424 fix: Terminal should swallow interactions
  lapce-data/src/keypress/mod.rs
  lapce-ui/src/terminal.rs
Labels: C-bug

#425 Don't allocate in terminal key handling
  lapce-ui/src/terminal.rs
Labels: C-cleanup

#379 Turn typing into an edit command
  lapce-data/src/buffer.rs
  lapce-data/src/buffer/data.rs
  lapce-data/src/buffer/decoration.rs
  lapce-data/src/editor.rs
  lapce-data/src/editor/commands/insert_chars.rs
  lapce-data/src/editor/commands/insert_tab.rs
  lapce-data/src/editor/commands/mod.rs
  lapce-data/src/editor/commands/test/mod.rs
Labels: C-tests

#426 fix: Open the Folder in the current window rather than a different one
  lapce-data/src/data.rs
Labels: C-bug

#386 Highlight active file on tab change, pt 1
  lapce-core/src/syntax.rs
  lapce-data/src/command.rs
  lapce-data/src/explorer.rs
  lapce-ui/src/editor/tab.rs
  lapce-ui/src/editor/tab_header_content.rs
  lapce-ui/src/explorer.rs
  lapce-ui/src/picker.rs
Labels: C-feature

#413 Clone selection vectors less
  lapce-data/src/buffer/data.rs
  lapce-data/src/data.rs
  lapce-data/src/editor.rs
  lapce-data/src/editor/commands/indentation.rs
  lapce-data/src/editor/commands/insert_tab.rs
  lapce-data/src/movement.rs
  lapce-ui/src/code_action.rs
Labels: C-cleanup

#429 Add Java syntax
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-core/src/language.rs
Labels: C-feature

#439 Remove `allow(unused_variables)` attributes
  lapce-data/src/buffer.rs
  lapce-data/src/data.rs
  lapce-data/src/editor.rs
  lapce-data/src/movement.rs
  lapce-data/src/palette.rs
  lapce-data/src/proxy.rs
  lapce-data/src/terminal.rs
  lapce-proxy/src/dispatch.rs
  lapce-proxy/src/lsp.rs
  lapce-ui/src/code_action.rs
  lapce-ui/src/palette.rs
  lapce-ui/src/scroll.rs
  lapce-ui/src/tab.rs
Labels: C-cleanup

#440 Clean up open folder/file
  lapce-data/src/data.rs
Labels: C-cleanup

#430 [TreeSitter] Add ruby language support
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-core/src/language.rs
Labels: C-feature

#320 Add markdown tree-sitter language
  lapce-core/Cargo.toml
  lapce-core/src/language.rs
Labels: C-feature

#443 Comment a couple of high-level data structs
  lapce-data/src/data.rs
Labels: A-documentation, C-improvement

#437 Fix cursor movement in non-vi mode terminal
  defaults/keymaps-common.toml
  lapce-data/src/terminal.rs
  lapce-ui/src/terminal.rs
Labels: C-bug

#452 support parsing the RUST_LOG env var
  lapce-ui/src/app.rs
  lapce-ui/src/lib.rs
  lapce-ui/src/logging.rs
Labels: C-feature, A-dev

#441 Create the fastdev profile
  Cargo.lock
  Cargo.toml
  lapce-data/Cargo.toml
  lapce-ui/Cargo.toml
Labels: C-feature, A-dev

#444 Build release versions using LTO
  .github/workflows/release.yml
  Cargo.toml
  Makefile
Labels: C-perf, A-distribution

#456 Fix markdown dependency
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-core/src/language.rs
Labels: C-bug

#453 Implement Markdown support for Hover
  Cargo.lock
  defaults/dark-theme.toml
  defaults/light-theme.toml
  lapce-data/Cargo.toml
  lapce-data/src/config.rs
  lapce-data/src/hover.rs
  lapce-proxy/src/lsp.rs
  lapce-ui/src/hover.rs
Labels: C-feature, A-editor
