Repository lapce/lapce, pull requests merged in 2022-07, with the labels that each got.

#715 Implement inlay hints
  Cargo.lock
  defaults/dark-theme.toml
  defaults/light-theme.toml
  defaults/settings.toml
  lapce-data/Cargo.toml
  lapce-data/src/command.rs
  lapce-data/src/config.rs
  lapce-data/src/document.rs
  lapce-data/src/editor.rs
  lapce-data/src/proxy.rs
  lapce-proxy/src/dispatch.rs
  lapce-proxy/src/lsp.rs
  lapce-rpc/src/proxy.rs
  lapce-ui/src/editor.rs
  lapce-ui/src/editor/view.rs
  lapce-ui/src/tab.rs
Labels: A-lsp

#722 Fix various inlay hint position bugs
  lapce-ui/src/editor.rs
  lapce-ui/src/editor/view.rs
Labels: A-lsp

#729 Sort inlay hints
  lapce-data/src/document.rs
Labels: A-lsp

#744 Handle LSP requests for hearing about file saving of specific files
  Cargo.lock
  lapce-proxy/Cargo.toml
  lapce-proxy/src/dispatch.rs
  lapce-proxy/src/lsp.rs
Labels: A-lsp

#735 Make ctrl+c=esc
  defaults/keymaps-common.toml
Labels: A-keymap

#728 feat: add option to use lsp from PATH
  lapce-proxy/src/plugin.rs
Labels: A-lsp, A-plugins

#748 Add setting for hover font family/size
  defaults/settings.toml
  lapce-data/src/config.rs
  lapce-ui/src/hover.rs
Labels: A-ui, C-improvement

#732 feat: add color option to file type svgs
  lapce-ui/src/editor/header.rs
  lapce-ui/src/editor/tab_header.rs
  lapce-ui/src/editor/tab_header_content.rs
  lapce-ui/src/explorer.rs
  lapce-ui/src/palette.rs
  lapce-ui/src/picker.rs
  lapce-ui/src/problem.rs
  lapce-ui/src/search.rs
  lapce-ui/src/source_control.rs
  lapce-ui/src/svg.rs
Labels: A-ui

#755 enter key in terminal scrolls down
  lapce-data/src/terminal.rs
Labels: A-terminal

#702 feat: add command to change file syntax language
  lapce-core/src/language.rs
  lapce-data/src/command.rs
  lapce-data/src/data.rs
  lapce-data/src/document.rs
  lapce-data/src/palette.rs
  lapce-ui/src/palette.rs
  lapce-ui/src/tab.rs
Labels: A-syntax

#781 fix plugin panel scroll bar
  lapce-ui/src/plugin.rs
Labels: A-ui

#789 Check lsp capabilities before sending commands
  lapce-proxy/src/buffer.rs
  lapce-proxy/src/lsp.rs
Labels: A-lsp

#799 Code lens fix
  lapce-data/src/data.rs
  lapce-data/src/document.rs
  lapce-data/src/editor.rs
  lapce-data/src/history.rs
  lapce-ui/src/editor.rs
  lapce-ui/src/editor/gutter.rs
  lapce-ui/src/editor/view.rs
Labels: A-ui, A-editor

#809 add ellipsis to plugin description
  lapce-ui/src/plugin.rs
Labels: A-ui

#805 Add LSP Goto Type Definition support
  lapce-core/src/command.rs
  lapce-data/src/editor.rs
  lapce-data/src/proxy.rs
  lapce-proxy/src/dispatch.rs
  lapce-proxy/src/lsp.rs
  lapce-rpc/src/proxy.rs
Labels: A-lsp

#803 Check if line is at the max in line styles
  lapce-core/src/style.rs
Labels: C-bug, A-ui

#806 Add next/previous tab commands and keybindings
  defaults/keymaps-macos.toml
  defaults/keymaps-nonmacos.toml
  lapce-core/src/command.rs
  lapce-data/src/command.rs
  lapce-data/src/data.rs
  lapce-ui/src/editor/tab.rs
  lapce-ui/src/editor/tab_header.rs
Labels: A-keymap

#824 Request utf8 from LSP if possible
  lapce-proxy/src/lsp.rs
Labels: A-lsp

#831 Fix goto ref on single references
  lapce-data/src/command.rs
  lapce-data/src/editor.rs
  lapce-ui/src/tab.rs
Labels: A-lsp

#835 Change proxy callbacks to specify their result type and do parsing beforehand
  lapce-data/src/command.rs
  lapce-data/src/completion.rs
  lapce-data/src/data.rs
  lapce-data/src/document.rs
  lapce-data/src/editor.rs
  lapce-data/src/explorer.rs
  lapce-data/src/history.rs
  lapce-data/src/hover.rs
  lapce-data/src/palette.rs
  lapce-data/src/picker.rs
  lapce-data/src/proxy.rs
  lapce-ui/src/tab.rs
Labels: A-dev

#841 Specify a field so that LSPs to avoid minor lsp-types bug
  lapce-proxy/src/lsp.rs
Labels: A-lsp

#849 Specify the workspace folder of the root uri if available
  lapce-proxy/src/lsp.rs
Labels: A-lsp

#850 Set the current directory when starting the LSP
  lapce-proxy/src/lsp.rs
Labels: A-lsp

#848 Separate plugin panel into two parts and improve loading message
  lapce-data/src/command.rs
  lapce-data/src/data.rs
  lapce-data/src/plugin.rs
  lapce-data/src/proxy.rs
  lapce-ui/src/plugin.rs
  lapce-ui/src/tab.rs
Labels: A-ui, A-plugins

#867 Use utf8 offsets instead of lsp_types Position
  lapce-data/src/command.rs
  lapce-data/src/data.rs
  lapce-data/src/db.rs
  lapce-data/src/editor.rs
  lapce-data/src/palette.rs
  lapce-ui/src/problem.rs
  lapce-ui/src/search.rs
  lapce-ui/src/tab.rs
Labels: A-dev

#873 Use generic parameter instead of separate structures
  lapce-data/src/command.rs
  lapce-data/src/data.rs
  lapce-data/src/document.rs
  lapce-data/src/editor.rs
  lapce-data/src/palette.rs
  lapce-ui/src/problem.rs
  lapce-ui/src/tab.rs
Labels: A-lsp

#869 Read files lossily, in case they are not utf8
  lapce-proxy/src/buffer.rs
Labels: A-unicode

#880 Add functionalities to enable, disable and remove plugins
  lapce-data/src/command.rs
  lapce-data/src/data.rs
  lapce-data/src/plugin.rs
  lapce-data/src/proxy.rs
  lapce-proxy/src/dispatch.rs
  lapce-proxy/src/lsp.rs
  lapce-proxy/src/plugin.rs
  lapce-rpc/src/core.rs
  lapce-rpc/src/plugin.rs
  lapce-rpc/src/proxy.rs
  lapce-ui/src/plugin.rs
  lapce-ui/src/tab.rs
Labels: C-feature, A-plugins

#887 don't paint tiny tab drags
  lapce-data/src/data.rs
  lapce-ui/src/editor/tab.rs
  lapce-ui/src/editor/tab_header_content.rs
  lapce-ui/src/panel.rs
  lapce-ui/src/tab.rs
Labels: A-ui

#884 Use UTF16 encoding for LSPs
  Cargo.lock
  lapce-core/src/buffer.rs
  lapce-core/src/encoding.rs
  lapce-core/src/lib.rs
  lapce-data/src/data.rs
  lapce-data/src/document.rs
  lapce-data/src/editor.rs
  lapce-proxy/Cargo.toml
  lapce-proxy/src/buffer.rs
  lapce-proxy/src/lsp.rs
Labels: A-lsp, A-unicode

#890 fixed spelling mistake in config.rs
  lapce-data/src/config.rs
Labels: A-dev, C-improvement

#899 Properly jump to line-col for search; Make line jumping not rely on the buffer being immediately open
  lapce-data/src/command.rs
  lapce-data/src/data.rs
  lapce-data/src/editor.rs
  lapce-ui/src/search.rs
  lapce-ui/src/tab.rs
Labels: C-bug, A-editor
