Repository lapce/lapce, pull requests merged in 2022-12, with the labels that each got.

#1831 Plugin settings shown on right click
  CHANGELOG.md
  lapce-ui/src/plugin.rs
Labels: A-ui

#1838 Don't use the active editor's view id for opening file diff
  lapce-ui/src/tab.rs
Labels: A-ui

#1834 Remove unnecessary vector allocation in `TerminalPanel::update`
  lapce-ui/src/terminal.rs
Labels: A-dev, C-perf

#1836 Remove vector allocation in `LapceTerminalPanelHeaderContent::update`
  lapce-ui/src/terminal.rs
Labels: A-dev, C-perf

#1835 Implement mouse keybinds
  .gitignore
  CHANGELOG.md
  lapce-data/src/keypress/keypress.rs
  lapce-data/src/keypress/loader.rs
  lapce-data/src/keypress/mod.rs
  lapce-ui/src/editor.rs
  lapce-ui/src/keymap.rs
  lapce-ui/src/tab.rs
Labels: A-keymap

#1841 Remove a lot of small vector allocation for `lapce_core::syntax::find_tag`
  lapce-core/src/buffer/mod.rs
  lapce-core/src/char_buffer.rs
  lapce-core/src/lib.rs
  lapce-data/src/document.rs
Labels: A-dev, C-perf

#1876 Implement Bracketed Paste in Lapce Terminal
  lapce-data/src/terminal.rs
Labels: A-terminal
