Repository lapce/lapce, pull requests merged in 2022-08, with the labels that each got.

#911 Use recv when receiving messages and stop checking when the channel closes
  lapce-proxy/src/plugin.rs
Labels: C-perf

#913 ci: add daily nightly build
  .github/workflows/release.yml
Labels: A-distribution

#914 Fix hotkey for redo
  defaults/keymaps-common.toml
  defaults/keymaps-macos.toml
  defaults/keymaps-nonmacos.toml
  lapce-data/src/keypress/keypress.rs
  lapce-data/src/keypress/mod.rs
Labels: C-bug, P-macos, A-keymap

#916 Don't show autocomplete after whitespace keys
  lapce-data/src/editor.rs
Labels: A-editor, C-improvement

#925 Open editors when applying text edits via code actions
  lapce-data/src/command.rs
  lapce-data/src/data.rs
  lapce-data/src/document.rs
  lapce-data/src/editor.rs
  lapce-ui/src/editor/view.rs
  lapce-ui/src/tab.rs
Labels: A-editor

#927 Make completion and palette pay attention to page-up/down
  defaults/keymaps-common.toml
  lapce-core/src/command.rs
  lapce-data/src/completion.rs
  lapce-data/src/editor.rs
  lapce-data/src/palette.rs
  lapce-ui/src/completion.rs
  lapce-ui/src/palette.rs
Labels: A-keymap, A-editor

#895 Adding Setting to control palette preview editor's width
  defaults/settings.toml
  lapce-data/src/config.rs
  lapce-ui/src/palette.rs
Labels: A-ui

#807 feat: add tree-sitter-wgsl
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-core/src/language.rs
  lapce-ui/Cargo.toml
Labels: A-syntax

#939 ci: fix macos artefacts path
  .github/workflows/release.yml
Labels: A-distribution

#937 Don't show autocomplete after backspacing over whitespace
  lapce-data/src/editor.rs
Labels: A-editor

#952 Fix crash on completion
  lapce-data/src/editor.rs
Labels: A-editor, C-crash 💥

#948 Add the ability to resize splits
  lapce-data/src/split.rs
  lapce-ui/src/explorer.rs
  lapce-ui/src/keymap.rs
  lapce-ui/src/panel.rs
  lapce-ui/src/plugin.rs
  lapce-ui/src/problem.rs
  lapce-ui/src/search.rs
  lapce-ui/src/settings.rs
  lapce-ui/src/source_control.rs
  lapce-ui/src/split.rs
  lapce-ui/src/terminal.rs
Labels: C-feature, A-ui, A-editor

#961 Fix calculation of problem mouse down position
  lapce-ui/src/problem.rs
Labels: A-ui

#962 Decrease padding in hover; fix todo
  lapce-data/src/markdown/mod.rs
Labels: A-ui

#893 Proxy refactor
  .github/workflows/release.yml
  Cargo.lock
  lapce-core/Cargo.toml
  lapce-core/src/buffer.rs
  lapce-data/Cargo.toml
  lapce-data/src/command.rs
  lapce-data/src/completion.rs
  lapce-data/src/config.rs
  lapce-data/src/data.rs
  lapce-data/src/db.rs
  lapce-data/src/document.rs
  lapce-data/src/editor.rs
  lapce-data/src/explorer.rs
  lapce-data/src/history.rs
  lapce-data/src/hover.rs
  lapce-data/src/palette.rs
  lapce-data/src/picker.rs
  lapce-data/src/plugin.rs
  lapce-data/src/proxy.rs
  lapce-data/src/terminal.rs
  lapce-proxy/Cargo.toml
  lapce-proxy/src/bin/lapce-proxy.rs
  lapce-proxy/src/buffer.rs
  lapce-proxy/src/directory.rs
  lapce-proxy/src/dispatch.rs
  lapce-proxy/src/lib.rs
  lapce-proxy/src/lsp.rs
  lapce-proxy/src/plugin.rs
  lapce-proxy/src/plugin/catalog.rs
  lapce-proxy/src/plugin/lsp.rs
  lapce-proxy/src/plugin/mod.rs
  lapce-proxy/src/plugin/psp.rs
  lapce-proxy/src/plugin/wasi.rs
  lapce-proxy/src/terminal.rs
  lapce-proxy/src/watcher.rs
  lapce-rpc/Cargo.toml
  lapce-rpc/src/core.rs
  lapce-rpc/src/lib.rs
  lapce-rpc/src/lsp.rs
  lapce-rpc/src/plugin.rs
  lapce-rpc/src/proxy.rs
  lapce-rpc/src/stdio.rs
  lapce-rpc/src/style.rs
  lapce-ui/Cargo.toml
  lapce-ui/src/app.rs
  lapce-ui/src/completion.rs
  lapce-ui/src/editor/tab_header.rs
  lapce-ui/src/editor/tab_header_content.rs
  lapce-ui/src/plugin.rs
  lapce-ui/src/tab.rs
  lapce-ui/src/window.rs
Labels: A-remote

#956 Adding A Refresh Button For The Context Menu Of The File Explorer
  lapce-data/src/command.rs
  lapce-ui/src/explorer.rs
Labels: C-feature, A-ui

#983 feat: add LapceUICommand::OpenURI
  Cargo.lock
  lapce-data/src/command.rs
  lapce-ui/Cargo.toml
  lapce-ui/src/tab.rs
Labels: C-feature, A-editor

#992 ci: run rustfmt and clippy for all platforms
  .github/workflows/ci.yml
  .github/workflows/pr.yml
Labels: A-dev
