Repository lapce/lapce, pull requests merged in 2023-06, with the labels that each got.

#2425 Impl completion lens
  CHANGELOG.md
  lapce-app/src/completion.rs
  lapce-app/src/config/editor.rs
  lapce-app/src/doc.rs
  lapce-app/src/editor.rs
  lapce-app/src/window_tab.rs
  lapce-core/src/buffer/rope_text.rs
Labels: A-lsp

#2426 Turn `RopeText` into a trait
  lapce-app/src/completion.rs
  lapce-app/src/doc.rs
  lapce-app/src/editor.rs
  lapce-app/src/editor/location.rs
  lapce-app/src/editor/movement.rs
  lapce-app/src/editor/view.rs
  lapce-app/src/main_split.rs
  lapce-app/src/palette.rs
  lapce-app/src/text_input.rs
  lapce-core/src/buffer/mod.rs
  lapce-core/src/buffer/rope_text.rs
  lapce-core/src/buffer/test.rs
  lapce-core/src/cursor.rs
  lapce-core/src/editor.rs
  lapce-core/src/indent.rs
  lapce-core/src/syntax/edit.rs
  lapce-data/src/atomic_soft_tabs.rs
  lapce-data/src/command.rs
  lapce-data/src/completion.rs
  lapce-data/src/data.rs
  lapce-data/src/document.rs
  lapce-data/src/editor.rs
  lapce-data/src/explorer.rs
  lapce-data/src/history.rs
  lapce-data/src/palette.rs
  lapce-data/src/rename.rs
  lapce-proxy/src/plugin/psp.rs
  lapce-ui/src/diff.rs
  lapce-ui/src/editor.rs
  lapce-ui/src/editor/gutter.rs
  lapce-ui/src/editor/view.rs
  lapce-ui/src/plugin.rs
  lapce-ui/src/settings.rs
  lapce-ui/src/tab.rs
  lapce-ui/src/title.rs
Labels: A-dev

#2441 Use Listener for commands
  lapce-app/src/app.rs
  lapce-app/src/code_action.rs
  lapce-app/src/editor.rs
  lapce-app/src/editor/view.rs
  lapce-app/src/file_explorer/node.rs
  lapce-app/src/keypress.rs
  lapce-app/src/lib.rs
  lapce-app/src/listener.rs
  lapce-app/src/palette.rs
  lapce-app/src/panel/debug_view.rs
  lapce-app/src/panel/global_search_view.rs
  lapce-app/src/panel/problem_view.rs
  lapce-app/src/rename.rs
  lapce-app/src/terminal/data.rs
  lapce-app/src/title.rs
  lapce-app/src/window.rs
  lapce-app/src/window_tab.rs
Labels: A-dev

#2444 Minor: Update log targets
  lapce-app/src/keypress.rs
  lapce-app/src/proxy/remote.rs
  lapce-app/src/proxy/ssh.rs
Labels: A-dev

#2478 load tree-sitter grammars dynamically, remove most grammars
  Cargo.lock
  lapce-app/Cargo.toml
  lapce-app/src/app.rs
  lapce-app/src/palette.rs
  lapce-core/Cargo.toml
  lapce-core/src/directory.rs
  lapce-core/src/language.rs
  lapce-core/src/syntax/highlight.rs
  lapce-data/src/palette.rs
  lapce-data/src/svg.rs
  lapce-proxy/src/terminal.rs
  lapce-ui/Cargo.toml
Labels: A-syntax

#2485 fix: re-implement reference checkout, include tags
  lapce-app/src/app.rs
  lapce-app/src/command.rs
  lapce-app/src/palette.rs
  lapce-app/src/palette/item.rs
  lapce-app/src/palette/kind.rs
  lapce-app/src/source_control.rs
  lapce-app/src/title.rs
  lapce-app/src/window_tab.rs
  lapce-proxy/src/dispatch.rs
  lapce-rpc/src/proxy.rs
  lapce-rpc/src/source_control.rs
Labels: A-ui, A-git
