Repository lapce/lapce, pull requests merged in 2023-01, with the labels that each got.

#1912 Minor: get rid of unneeded nesting in phantom text code
  lapce-data/src/document.rs
Labels: A-dev

#1911 Fix cursor movement on selections with arrow keys
  CHANGELOG.md
  lapce-data/src/document.rs
Labels: A-editor

#1902 Improve `get_file_node[_mut]` efficiency
  lapce-rpc/src/file.rs
  lapce-ui/src/picker.rs
Labels: A-dev

#1917 Simplifying `lapce_ui::settings::ThemeSection::new`
  lapce-ui/src/settings.rs
Labels: A-ui, C-perf

#1856 Highlight git/VCS modified files in explorer, palette, and buffer tabs
  CHANGELOG.md
  Cargo.lock
  lapce-data/src/data.rs
  lapce-data/src/editor.rs
  lapce-data/src/palette.rs
  lapce-data/src/source_control.rs
  lapce-proxy/src/dispatch.rs
  lapce-ui/Cargo.toml
  lapce-ui/src/editor/tab_header_content.rs
  lapce-ui/src/explorer.rs
  lapce-ui/src/palette.rs
  lapce-ui/src/source_control.rs
  lapce-ui/src/tab.rs
Labels: A-ui

#1863 Optimization of `lapce_ui::terminal::TerminalPanel::event`
  Cargo.lock
  lapce-ui/Cargo.toml
  lapce-ui/src/terminal.rs
Labels: A-dev, C-perf

#1574 Open editors list can now be collapsed by clicking it
  lapce-ui/src/explorer.rs
  lapce-ui/src/panel.rs
  lapce-ui/src/plugin.rs
Labels: A-ui

#1939 Register buffer when saving-as a new file
  CHANGELOG.md
  lapce-proxy/src/dispatch.rs
Labels: C-bug

#1938 Implement dropdown widget; Use dropdown widget for settings
  CHANGELOG.md
  defaults/settings.toml
  lapce-data/src/command.rs
  lapce-data/src/config.rs
  lapce-data/src/dropdown.rs
  lapce-data/src/lib.rs
  lapce-data/src/list.rs
  lapce-data/src/settings.rs
  lapce-ui/src/dropdown.rs
  lapce-ui/src/lib.rs
  lapce-ui/src/list.rs
  lapce-ui/src/settings.rs
Labels: A-ui

#1941 Add docs; style-changes; remove unused commands
  lapce-data/src/command.rs
  lapce-data/src/data.rs
  lapce-data/src/document.rs
  lapce-data/src/editor.rs
  lapce-data/src/explorer.rs
  lapce-data/src/history.rs
  lapce-data/src/hover.rs
  lapce-data/src/keypress/mod.rs
  lapce-data/src/palette.rs
  lapce-data/src/proxy.rs
  lapce-data/src/source_control.rs
  lapce-ui/src/editor/view.rs
  lapce-ui/src/hover.rs
  lapce-ui/src/palette.rs
  lapce-ui/src/settings.rs
  lapce-ui/src/source_control.rs
  lapce-ui/src/split.rs
  lapce-ui/src/tab.rs
  lapce-ui/src/window.rs
Labels: A-dev

#1968 Implement completion lens
  CHANGELOG.md
  defaults/settings.toml
  lapce-data/src/completion.rs
  lapce-data/src/config.rs
  lapce-data/src/document.rs
  lapce-data/src/editor.rs
  lapce-ui/src/completion.rs
Labels: A-ui, A-editor

#1940 cargo: migrate to workspace.dependencies
  Cargo.lock
  Cargo.toml
  lapce-core/Cargo.toml
  lapce-data/Cargo.toml
  lapce-proxy/Cargo.toml
  lapce-rpc/Cargo.toml
  lapce-ui/Cargo.toml
Labels: A-dev

#1992 Add serde feature req to indexmap dep
  Cargo.toml
Labels: A-dev

#2000 Add some documentation and tests
  lapce-core/src/buffer/mod.rs
  lapce-core/src/buffer/rope_text.rs
  lapce-data/src/data.rs
  lapce-data/src/document.rs
Labels: A-dev

#1991 Implement rendering of images in markdown views
  CHANGELOG.md
  Cargo.lock
  defaults/settings.toml
  icons/codicons/refresh.svg
  lapce-data/Cargo.toml
  lapce-data/src/command.rs
  lapce-data/src/config.rs
  lapce-data/src/data.rs
  lapce-data/src/hover.rs
  lapce-data/src/images.rs
  lapce-data/src/lib.rs
  lapce-data/src/markdown/layout_content.rs
  lapce-data/src/markdown/mod.rs
  lapce-data/src/plugin.rs
  lapce-ui/src/completion.rs
  lapce-ui/src/hover.rs
  lapce-ui/src/plugin.rs
  lapce-ui/src/signature.rs
  lapce-ui/src/tab.rs
Labels: A-ui

#2036 Fix cursor movement on selections with arrow up/down keys
  CHANGELOG.md
  lapce-data/src/document.rs
Labels: A-keymap

#2072 fix: remove ssh timeout option on windows
  CHANGELOG.md
  lapce-data/src/proxy.rs
Labels: P-windows, A-remote

#2071 feat: add command and keybinds to delete line
  CHANGELOG.md
  defaults/keymaps-macos.toml
  defaults/keymaps-nonmacos.toml
  lapce-core/src/command.rs
  lapce-core/src/editor.rs
Labels: C-feature, A-keymap, A-editor

#2070 fix: set language environment in proper way
  Cargo.lock
  lapce-proxy/Cargo.toml
  lapce-proxy/src/terminal.rs
Labels: P-macos

#2069 fix: find repository if it's not in current workspace path
  CHANGELOG.md
  lapce-proxy/src/dispatch.rs
Labels: A-git

#2075 fix: remove regex, parse remote as URL
  lapce-proxy/src/dispatch.rs
Labels: A-git

#2074 feat: add Ctrl+{a,e,k} keybinds on macOS
  CHANGELOG.md
  defaults/keymaps-macos.toml
  lapce-core/src/command.rs
  lapce-core/src/editor.rs
  lapce-data/src/palette.rs
Labels: P-macos, A-keymap
