Repository lapce/lapce, pull requests merged in 2024-03, with the labels that each got.

#3031 Focus on app_view so that find receives keypresses
  CHANGELOG.md
  lapce-app/src/app.rs
  lapce-app/src/editor/view.rs
  lapce-app/src/window.rs
Labels: A-ui

#3047 Implement line-ending switching
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  defaults/settings.toml
  lapce-app/Cargo.toml
  lapce-app/src/app.rs
  lapce-app/src/command.rs
  lapce-app/src/config/editor.rs
  lapce-app/src/doc.rs
  lapce-app/src/editor.rs
  lapce-app/src/focus_text.rs
  lapce-app/src/palette.rs
  lapce-app/src/palette/item.rs
  lapce-app/src/palette/kind.rs
  lapce-app/src/status.rs
  lapce-app/src/text_input.rs
  lapce-app/src/window_tab.rs
Labels: A-ui, A-editor

#3053 Tooltips
  CHANGELOG.md
  defaults/dark-theme.toml
  defaults/light-theme.toml
  lapce-app/src/app.rs
  lapce-app/src/config.rs
  lapce-app/src/config/color.rs
  lapce-app/src/doc.rs
  lapce-app/src/editor.rs
  lapce-app/src/editor/view.rs
  lapce-app/src/file_explorer/view.rs
  lapce-app/src/panel/debug_view.rs
  lapce-app/src/panel/global_search_view.rs
  lapce-app/src/panel/plugin_view.rs
  lapce-app/src/panel/terminal_view.rs
  lapce-app/src/panel/view.rs
  lapce-app/src/status.rs
  lapce-app/src/title.rs
Labels: A-ui

#3054 Focus on app_view when creating the view
  lapce-app/src/app.rs
Labels: A-ui

#3055 Move line up/down keybinds in insert to macos
  defaults/keymaps-common.toml
  defaults/keymaps-macos.toml
  defaults/keymaps-nonmacos.toml
Labels: A-keymap

#3068 Fix scrolling in file explorer
  lapce-app/src/file_explorer/view.rs
Labels: A-ui

#3069 Implement arbitrary theme variables
  CHANGELOG.md
  defaults/dark-theme.toml
  defaults/light-theme.toml
  extra/schemas/color-theme.json
  lapce-app/src/config.rs
  lapce-app/src/config/color.rs
  lapce-app/src/config/color_theme.rs
  lapce-app/src/settings.rs
Labels: A-ui, A-plugins

#3076 Add plugin-path for launching with a plugin in a folder
  lapce-app/src/app.rs
  lapce-app/src/config.rs
  lapce-app/src/plugin.rs
  lapce-app/src/proxy.rs
  lapce-app/src/terminal/data.rs
  lapce-app/src/terminal/panel.rs
  lapce-app/src/terminal/tab.rs
  lapce-app/src/window.rs
  lapce-app/src/window_tab.rs
  lapce-proxy/src/dispatch.rs
  lapce-proxy/src/plugin/catalog.rs
  lapce-proxy/src/plugin/wasi.rs
  lapce-rpc/src/proxy.rs
Labels: A-plugins, A-cli

#3086 Foldable panel sections
  CHANGELOG.md
  defaults/icon-theme.toml
  lapce-app/src/app.rs
  lapce-app/src/config/icon.rs
  lapce-app/src/file_explorer/view.rs
  lapce-app/src/panel/debug_view.rs
  lapce-app/src/panel/plugin_view.rs
  lapce-app/src/panel/problem_view.rs
  lapce-app/src/panel/source_control_view.rs
  lapce-app/src/panel/view.rs
Labels: A-ui

#3089 fix panel resizing bug
  lapce-app/src/app.rs
Labels: A-ui

#3095 Add setting to toggle open editors section
  CHANGELOG.md
  defaults/settings.toml
  lapce-app/src/config/ui.rs
  lapce-app/src/file_explorer/view.rs
  lapce-app/src/panel/view.rs
Labels: A-ui

#3096 Add text color if file is changed according to source control
  CHANGELOG.md
  lapce-app/src/file_explorer/view.rs
  lapce-rpc/src/file.rs
  lapce-rpc/src/source_control.rs
Labels: A-ui

#3118 Editors struct
  Cargo.lock
  lapce-app/src/app.rs
  lapce-app/src/doc.rs
  lapce-app/src/editor.rs
  lapce-app/src/editor/diff.rs
  lapce-app/src/editor/gutter.rs
  lapce-app/src/editor/view.rs
  lapce-app/src/editor_tab.rs
  lapce-app/src/file_explorer/data.rs
  lapce-app/src/file_explorer/view.rs
  lapce-app/src/global_search.rs
  lapce-app/src/keymap.rs
  lapce-app/src/keypress.rs
  lapce-app/src/main_split.rs
  lapce-app/src/palette.rs
  lapce-app/src/panel/global_search_view.rs
  lapce-app/src/panel/plugin_view.rs
  lapce-app/src/plugin.rs
  lapce-app/src/rename.rs
  lapce-app/src/settings.rs
  lapce-app/src/source_control.rs
  lapce-app/src/status.rs
  lapce-app/src/text_input.rs
  lapce-app/src/window_tab.rs
Labels: A-dev
